import math

# Data index
TALLY = 0

# Tallies
TALLY_GLOBAL = 0
TALLY_CELL = 1
TALLY_SURFACE = 2
TALLY_MESH = 3

# Meshes
MESH_UNIFORM = 0
MESH_STRUCTURED = 1

# Tally scores
SCORE_FLUX = 0
SCORE_DENSITY = 1
SCORE_COLLISION = 2
SCORE_CAPTURE = 3
SCORE_FISSION = 4
SCORE_NET_CURRENT = 5
SCORE_MU_SQ = 6
SCORE_TIME_MOMENT_FLUX = 7
SCORE_SPACE_MOMENT_FLUX = 8
SCORE_TIME_MOMENT_CURRENT = 9
SCORE_SPACE_MOMENT_CURRENT = 10
SCORE_TIME_MOMENT_MU_SQ = 11
SCORE_SPACE_MOMENT_MU_SQ = 12
SCORE_TRACKS = 13
SCORE_SECOND_MOMENT = 14
# Tally multipliers
MULTIPLIER_ENERGY = 0

# Boundary condition
BC_NONE = 0
BC_VACUUM = 1
BC_REFLECTIVE = 2

# Cell fill
FILL_MATERIAL = 0
FILL_UNIVERSE = 1
FILL_LATTICE = 2
FILL_NONE = 3

# Region
REGION_HALFSPACE = 0
REGION_INTERSECTION = 1
REGION_UNION = 2
REGION_COMPLEMENT = 3
REGION_ALL = 4

# Surface type
SURFACE_PLANE_X = 0
SURFACE_PLANE_Y = 2
SURFACE_PLANE_Z = 3
SURFACE_PLANE = 4
SURFACE_CYLINDER_X = 5
SURFACE_CYLINDER_Y = 6
SURFACE_CYLINDER_Z = 7
SURFACE_SPHERE = 8
SURFACE_QUADRIC = 9

# Boolean operator
BOOL_AND = -1
BOOL_OR = -2
BOOL_NOT = -3

# Universe
UNIVERSE_ROOT = 0

# Events
#   The << operator represents a bitshift.
#   Each event is assigned 1 << X, which is equal to 2 to the power of X.
EVENT_NONE = 1 << 0
# Geometry events
EVENT_SURFACE_CROSSING = 1 << 1
EVENT_LATTICE_CROSSING = 1 << 2
EVENT_LOST = 1 << 3
# Collision/reaction events
EVENT_COLLISION = 1 << 4
# Miscellanies
EVENT_TIME_CENSUS = 1 << 5
EVENT_TIME_BOUNDARY = 1 << 6

# Materials
MATERIAL = 0
MATERIAL_MG = 1
MATERIAL_ELEMENTAL = 2

# Reactions
REACTION_TOTAL = 0
REACTION_NEUTRON_ELASTIC_SCATTERING = 1
REACTION_NEUTRON_CAPTURE = 2
REACTION_NEUTRON_INELASTIC_SCATTERING = 3
REACTION_NEUTRON_FISSION = 4
REACTION_NEUTRON_FISSION_PROMPT = 5
REACTION_NEUTRON_FISSION_DELAYED = 6

# Particle types
PARTICLE_NEUTRON = 0

# Data
DATA_NONE = 0
DATA_TABLE = 1
DATA_POLYNOMIAL = 2

# Distribution
DISTRIBUTION_NONE = 0
DISTRIBUTION_PMF = 1
DISTRIBUTION_TABULATED = 2
DISTRIBUTION_MULTITABLE = 3
DISTRIBUTION_LEVEL_SCATTERING = 4
DISTRIBUTION_EVAPORATION = 5
DISTRIBUTION_MAXWELLIAN = 6
DISTRIBUTION_KALBACH_MANN = 7
DISTRIBUTION_TABULATED_ENERGY_ANGLE = 8
DISTRIBUTION_N_BODY = 9

# Anguler distribution type
ANGLE_ISOTROPIC = 0
ANGLE_DISTRIBUTED = 1
ANGLE_ENERGY_CORRELATED = 2

# Referance frame
REFERENCE_FRAME_LAB = 0
REFERENCE_FRAME_COM = 1

# Interpolation law
INTERPOLATION_LINEAR = 2
INTERPOLATION_LOG = 5

# Gyration raius type
GYRATION_RADIUS_ALL = 0
GYRATION_RADIUS_INFINITE_X = 1
GYRATION_RADIUS_INFINITE_Y = 2
GYRATION_RADIUS_INFINITE_Z = 3
GYRATION_RADIUS_ONLY_X = 4
GYRATION_RADIUS_ONLY_Y = 5
GYRATION_RADIUS_ONLY_Z = 6

# Population control
PCT_NONE = 0
PCT_COMBING = 1
PCT_COMBING_WEIGHT = 2
PCT_SPLITTING_ROULETTE = 3
PCT_SPLITTING_ROULETTE_WEIGHT = 4

# Misc.
TINY = 1e-10
COINCIDENCE_TOLERANCE = TINY
COINCIDENCE_TOLERANCE_DIRECTION = 1e-5
COINCIDENCE_TOLERANCE_ENERGY = 1e-5
COINCIDENCE_TOLERANCE_TIME = TINY * 1e-2
INF = 1e10
PI = math.pi
PI_SQRT = math.sqrt(PI)
PI_HALF = PI / 2.0
BANKMAX = 100  # Default maximum active bank

# Axes
AXIS_X = 0
AXIS_Y = 1
AXIS_Z = 2
AXIS_T = 3

# Physics
LIGHT_SPEED = 2.99792458e10  # cm/s
NEUTRON_MASS = 939.565413e6  # eV/c^2
BOLTZMANN_K = 8.61733326e-5  # eV/K
THERMAL_THRESHOLD_FACTOR = 400

# Weight Windows Methods
WW_USER = 0
WW_PREVIOUS = 1
# Weight Windows Modifications
WW_MIN = 0
WW_WOLLABER = 1
