import math

# Data index
TALLY = 0

# Tally types
TALLY_SURFACE_CROSSING = 0
TALLY_COLLISION = 1
TALLY_TRACKLENGTH = 2

# Meshes
MESH_UNIFORM = 0
MESH_STRUCTURED = 1

# Tally scores
## Tracklength
SCORE_FLUX = 0
SCORE_DENSITY = 1
SCORE_COLLISION = 2
SCORE_CAPTURE = 3
SCORE_FISSION = 4
SCORE_SECOND_MOMENT_X = 5
SCORE_SECOND_MOMENT_Y = 6
SCORE_SECOND_MOMENT_Z = 7
## Surface-crossing
SCORE_CURRENT_NET = 100
SCORE_CURRENT_IN = 101
SCORE_CURRENT_OUT = 102
## Collision
SCORE_ENERGY_DEPOSITION = 200

# Supported tally scores for estimator types
SUPPORTED_SCORES_SURFACE_CROSSING = {"current-net", "current-in", "current-out"}
SUPPORTED_SCORES_TRACKLENGTH = {"flux", "density", "collision", "capture", "fission","second_moment_x","second_moment_y","second_moment_z"}
SUPPORTED_SCORES_COLLISION = {"energy_deposition"}
SUPPORTED_SCORES = (
    SUPPORTED_SCORES_SURFACE_CROSSING
    | SUPPORTED_SCORES_TRACKLENGTH
    | SUPPORTED_SCORES_COLLISION
)

# Boundary condition
BC_NONE = 0
BC_VACUUM = 1
BC_REFLECTIVE = 2

# Cell fill
FILL_MATERIAL = 0
FILL_UNIVERSE = 1
FILL_LATTICE = 2
FILL_NONE = 3

# Region
REGION_HALFSPACE = 0
REGION_INTERSECTION = 1
REGION_UNION = 2
REGION_COMPLEMENT = 3
REGION_ALL = 4

# Surface type
SURFACE_PLANE_X = 1
SURFACE_PLANE_Y = 2
SURFACE_PLANE_Z = 3
SURFACE_PLANE = 4
SURFACE_CYLINDER_X = 5
SURFACE_CYLINDER_Y = 6
SURFACE_CYLINDER_Z = 7
SURFACE_CYLINDER = 8
SURFACE_SPHERE = 9
SURFACE_QUADRIC = 10
SURFACE_CONE_X = 11
SURFACE_CONE_Y = 12
SURFACE_CONE_Z = 13
SURFACE_TORUS_X = 14
SURFACE_TORUS_Y = 15
SURFACE_TORUS_Z = 16
SURFACE_TORUS = 17

# Boolean operator
BOOL_AND = -1
BOOL_OR = -2
BOOL_NOT = -3

# Universe
UNIVERSE_ROOT = 0

# Events
#   The << operator represents a bitshift.
#   Each event is assigned 1 << X, which is equal to 2 to the power of X.
EVENT_NONE = 1 << 0
# Geometry events
EVENT_SURFACE_CROSSING = 1 << 1
EVENT_LATTICE_CROSSING = 1 << 2
EVENT_LOST = 1 << 3
# Collision/reaction events
EVENT_COLLISION = 1 << 4
# Miscellanies
EVENT_TIME_CENSUS = 1 << 5
EVENT_TIME_BOUNDARY = 1 << 6

# Materials
MATERIAL = 0
MATERIAL_MG = 1
MATERIAL_ELEMENTAL = 2

# Reactions
NEUTRON_REACTION_TOTAL = 0
NEUTRON_REACTION_ELASTIC_SCATTERING = 1
NEUTRON_REACTION_CAPTURE = 2
NEUTRON_REACTION_INELASTIC_SCATTERING = 3
NEUTRON_REACTION_FISSION = 4
NEUTRON_REACTION_FISSION_PROMPT = 5
NEUTRON_REACTION_FISSION_DELAYED = 6
ELECTRON_REACTION_TOTAL = 100
ELECTRON_REACTION_ELASTIC_SCATTERING = 101
ELECTRON_REACTION_ELASTIC_SMALL_ANGLE = 102
ELECTRON_REACTION_ELASTIC_LARGE_ANGLE = 103
ELECTRON_REACTION_IONIZATION = 104
ELECTRON_REACTION_BREMSSTRAHLUNG = 105
ELECTRON_REACTION_EXCITATION = 106

# Particle types
PARTICLE_NEUTRON = 0
PARTICLE_ELECTRON = 1
PARTICLE_PROTON = 2

# Data
DATA_NONE = 0
DATA_TABLE = 1
DATA_POLYNOMIAL = 2

# Distribution
DISTRIBUTION_NONE = 0
DISTRIBUTION_PMF = 1
DISTRIBUTION_TABULATED = 2
DISTRIBUTION_MULTITABLE = 3
DISTRIBUTION_LEVEL_SCATTERING = 4
DISTRIBUTION_EVAPORATION = 5
DISTRIBUTION_MAXWELLIAN = 6
DISTRIBUTION_KALBACH_MANN = 7
DISTRIBUTION_TABULATED_ENERGY_ANGLE = 8
DISTRIBUTION_N_BODY = 9

# Anguler distribution type
ANGLE_ISOTROPIC = 0
ANGLE_DISTRIBUTED = 1
ANGLE_ENERGY_CORRELATED = 2

# Referance frame
REFERENCE_FRAME_LAB = 0
REFERENCE_FRAME_COM = 1

# Interpolation law
INTERPOLATION_HISTOGRAM = 1
INTERPOLATION_LINEAR = 2
INTERPOLATION_SEMILOGX = 3
INTERPOLATION_SEMILOGY = 4
INTERPOLATION_LOG = 5

# Gyration raius type
GYRATION_RADIUS_ALL = 0
GYRATION_RADIUS_INFINITE_X = 1
GYRATION_RADIUS_INFINITE_Y = 2
GYRATION_RADIUS_INFINITE_Z = 3
GYRATION_RADIUS_ONLY_X = 4
GYRATION_RADIUS_ONLY_Y = 5
GYRATION_RADIUS_ONLY_Z = 6

# Population control
PCT_NONE = 0
PCT_COMBING = 1
PCT_COMBING_WEIGHT = 2
PCT_SPLITTING_ROULETTE = 3
PCT_SPLITTING_ROULETTE_WEIGHT = 4

# Misc.
TINY = 1e-10
COINCIDENCE_TOLERANCE = TINY
COINCIDENCE_TOLERANCE_DIRECTION = 1e-5
COINCIDENCE_TOLERANCE_ENERGY = 1e-5
COINCIDENCE_TOLERANCE_TIME = TINY * 1e-2
INF = 1e10
PI = math.pi
PI_SQRT = math.sqrt(PI)
PI_HALF = PI / 2.0
BANKMAX = 100  # Default maximum active bank
MAX_BISECTION_ITERATIONS = 48

# Axes
AXIS_X = 0
AXIS_Y = 1
AXIS_Z = 2
AXIS_T = 3

# Physics
LIGHT_SPEED = 2.99792458e10  # cm/s
NEUTRON_MASS = 939.565413e6  # eV/c^2
ELECTRON_MASS = 510.99895069e3  # eV/c^2
BOLTZMANN_K = 8.61733326e-5  # eV/K
ELECTRON_CUTOFF_ENERGY = 100  # eV
MU_CUTOFF = 0.999999
THERMAL_THRESHOLD_FACTOR = 400

# Weight Windows Methods
WW_USER = 0
WW_PREVIOUS = 1
# Weight Windows Modifications
WW_MIN = 0
WW_WOLLABER = 1

# ======================================================================================
# GPU settings
# ======================================================================================

# GPU strategies
GPU_STRATEGY_SIMPLE_ASYNC = 0
GPU_STRATEGY_ASYNC = 0
GPU_STRATEGY_EVENT = 1

# GPU async. types
GPU_ASYNC_SIMPLE = 0

# GPU storage types
GPU_STORAGE_SEPARATE = 0
GPU_STORAGE_MANAGED = 1
GPU_STORAGE_UNITED = 2
